spring.application.name=LostAndFound
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/db2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=261216
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:org/example/lostandfound/mapper/*.xml

mybatis.type-aliases-package=org.example.lostandfound.pojo


logging.level.root=info
logging.level.org.example.lostandfound=debug


server.tomcat.uri-encoding=UTF-8

spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=100
